### PR TITLE
Add icon for required columns

### LINKED ISSUE #189: Restore the dropper icon for tables schema, with required columns
[The documentation for “Tables with arguments"](https://osquery.readthedocs.io/en/stable/introduction/sql/#tables-with-arguments) says “These tables, and their columns, are flagged by a dropper icon in the schema documentation as requiring a column or as using a column to generate additional information.”   However, this dropper icon is not present in the schema section of the current website.

I think this is referring to tables that have one or more columns that are `required=True`. Should this be an indication on the table, then, or an indication on the column? I would favor it being marked in the column description.

I failed to find a time when a dropper icon might have appeared. There doesn't appear to have been one in https://github.com/osquery/osquery-site/tree/source/src/components/Icon/svg

### PR DESCRIPTION
**Pull request by DominusKelvin**
This PR resolves #189

Here is a screenshot of how the icon renders for the required columns.

CleanShot 2022-08-05 at 23 02 01@2x

CleanShot 2022-08-05 at 22 59 56@2x

### CODE REVIEW

**Review by directionless — APPROVED** [review]
I can't test this, but LGTM! 

Thanks for updating it

**Comment by DominusKelvin** [comment]
> I can't test this, but LGTM!
> 
> Thanks for updating it

Thanks

**Comment by DominusKelvin** [comment]
@directionless, do you know if there is a design to add legends for icons like the one representing required columns in WHERE statements that this PR addresses?

Might be useful to have sort of a legend on the schema page.

**Comment by directionless** [comment]
I have no designs other than what was linked in #189

**Pull request merged**
